language: node_js
node_js:
    - 'lts/*'
sudo: false
cache: npm
script:
    - npm test
    - npm run lint:check
    - npm run build
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN # Set in the settings page of your repository
    keep-history: true
    on:
        branch: develop
    local-dir: public

# Set up Slack notifications:
# travis encrypt "<apikey>" --add notifications.slack
